### ISSUE TITLE
[Feature] CustomEvent 추가

### ISSUE THREAD

**Issue by ghost** [SkyLineLab/kapi#1]
https://developer.mozilla.org/ko/docs/Web/API/CustomEvent/CustomEvent
사용자가 마음대로 이벤트를 등록하고 보낼 수 있게합시다!

**Comment by naijun0403** [comment]
`CustomEvent`는 웹과 매우 긴밀한 관련이 있습니다, 이를 테면 `CustomEvent` 이벤트 리스너를 등록하는건
```javascript
window.addListener('test', () => {});

// 또는

document.createElement('test').addListener('test', () => {});
```
식으로 등록해야합니다.

그러나 이건 웹의 api랑 같이 사용해야합니다.

단순 이벤트 리스너를 등록 해제하고, 이를 emit하게 하는건 `EventEmitter`를 넣어두던가, `BotClient` 메서드에 emit를 추가하는 쪽으로 가는편이 더 나아보입니다.

**Comment by ghost** [comment]
`emit`대신 `dispatchEvent`가 직관성 측면에서 더 나을 것 같습니다.
그 외 추가적인 변경사항이 많이 필요한데 PR을 넣으면 될까요?

**Comment by naijun0403** [comment]
> `emit`대신 `dispatchEvent`가 직관성 측면에서 더 나을 것 같습니다.
> 그 외 추가적인 변경사항이 많이 필요한데 PR을 넣으면 될까요?

PR은 언제나 환영입니다! 원하시는 기능을 넣어주시면 리뷰해드리겠습니다.
